import 'server-only';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { QuoteClientKind, QuoteStatus } from '../domain/quote';
import { QUOTE_COLUMNS, type QuoteLineRow, type QuoteRow } from './quote-service';

// Lectures pour l'interface. Client service_role : chaque requête est bornée
// explicitement à l'organisme du membre connecté.
type Sb = SupabaseClient;

export type QuoteSummary = {
  id: string;
  reference: string;
  status: QuoteStatus;
  clientKind: QuoteClientKind;
  clientName: string;
  recipientName: string | null;
  recipientEmail: string | null;
  object: string;
  totalCents: number;
  subtotalCents: number;
  validUntil: string;
  issuedOn: string;
  sentAt: string | null;
  signedAt: string | null;
  documentId: string | null;
  autoGenerated: boolean;
  learnerCount: number;
  invoice: { id: string; reference: string; status: string } | null;
};

async function clientNames(
  sb: Sb,
  quotes: Array<Pick<QuoteRow, 'company_id' | 'learner_id'>>,
): Promise<{ companies: Map<string, string>; learners: Map<string, string> }> {
  const companyIds = [...new Set(quotes.map((q) => q.company_id).filter((v): v is string => !!v))];
  const learnerIds = [...new Set(quotes.map((q) => q.learner_id).filter((v): v is string => !!v))];
  const [{ data: cRows }, { data: lRows }] = await Promise.all([
    companyIds.length
      ? sb.schema('app').from('companies').select('id, name').in('id', companyIds)
      : Promise.resolve({ data: [] }),
    learnerIds.length
      ? sb.schema('app').from('learners').select('id, first_name, last_name').in('id', learnerIds)
      : Promise.resolve({ data: [] }),
  ]);
  return {
    companies: new Map(((cRows ?? []) as Array<{ id: string; name: string }>).map((c) => [c.id, c.name])),
    learners: new Map(
      ((lRows ?? []) as Array<{ id: string; first_name: string; last_name: string }>).map((l) => [
        l.id,
        `${l.first_name} ${l.last_name}`.trim(),
      ]),
    ),
  };
}

async function summarize(sb: Sb, rows: QuoteRow[]): Promise<QuoteSummary[]> {
  if (rows.length === 0) return [];
  const ids = rows.map((r) => r.id);
  const [names, { data: links }, { data: invRows }] = await Promise.all([
    clientNames(sb, rows),
    sb.schema('app').from('quote_dossiers').select('quote_id').in('quote_id', ids),
    sb
      .schema('app')
      .from('invoices')
      .select('id, reference, status, quote_id')
      .in('quote_id', ids)
      .is('deleted_at', null)
      .neq('status', 'cancelled'),
  ]);
  const counts = new Map<string, number>();
  for (const l of (links ?? []) as Array<{ quote_id: string }>) counts.set(l.quote_id, (counts.get(l.quote_id) ?? 0) + 1);
  const invoices = new Map(
    ((invRows ?? []) as Array<{ id: string; reference: string; status: string; quote_id: string }>).map((i) => [
      i.quote_id,
      { id: i.id, reference: i.reference, status: i.status },
    ]),
  );

  return rows.map((q) => ({
    id: q.id,
    reference: q.reference,
    status: q.status,
    clientKind: q.client_kind,
    clientName:
      (q.client_kind === 'company'
        ? q.company_id && names.companies.get(q.company_id)
        : q.learner_id && names.learners.get(q.learner_id)) ||
      q.recipient_name ||
      '—',
    recipientName: q.recipient_name,
    recipientEmail: q.recipient_email,
    object: q.object,
    totalCents: Number(q.total_cents),
    subtotalCents: Number(q.subtotal_cents),
    validUntil: q.valid_until,
    issuedOn: q.issued_on,
    sentAt: q.sent_at,
    signedAt: q.signed_at,
    documentId: q.document_id,
    autoGenerated: q.auto_generated,
    learnerCount: counts.get(q.id) ?? 0,
    invoice: invoices.get(q.id) ?? null,
  }));
}

export async function loadQuotesForDossier(sb: Sb, dossierId: string, organizationId: string): Promise<QuoteSummary[]> {
  const { data: links } = await sb.schema('app').from('quote_dossiers').select('quote_id').eq('dossier_id', dossierId);
  const ids = ((links ?? []) as Array<{ quote_id: string }>).map((l) => l.quote_id);
  if (ids.length === 0) return [];
  const { data } = await sb
    .schema('app')
    .from('quotes')
    .select(QUOTE_COLUMNS)
    .in('id', ids)
    .eq('organization_id', organizationId)
    .is('deleted_at', null)
    .order('created_at', { ascending: false });
  return summarize(sb, (data ?? []) as unknown as QuoteRow[]);
}

export async function loadQuotesForSession(sb: Sb, sessionId: string, organizationId: string): Promise<QuoteSummary[]> {
  const { data: links } = await sb.schema('app').from('session_dossiers').select('dossier_id').eq('session_id', sessionId);
  const dossierIds = ((links ?? []) as Array<{ dossier_id: string }>).map((l) => l.dossier_id);
  const { data: qd } = dossierIds.length
    ? await sb.schema('app').from('quote_dossiers').select('quote_id').in('dossier_id', dossierIds)
    : { data: [] };
  const ids = [...new Set(((qd ?? []) as Array<{ quote_id: string }>).map((l) => l.quote_id))];
  if (ids.length === 0) return [];
  const { data } = await sb
    .schema('app')
    .from('quotes')
    .select(QUOTE_COLUMNS)
    .in('id', ids)
    .eq('organization_id', organizationId)
    .is('deleted_at', null)
    .order('created_at', { ascending: true });
  return summarize(sb, (data ?? []) as unknown as QuoteRow[]);
}

export async function listQuotes(
  sb: Sb,
  organizationId: string,
  status: QuoteStatus | null,
): Promise<QuoteSummary[]> {
  let query = sb
    .schema('app')
    .from('quotes')
    .select(QUOTE_COLUMNS)
    .eq('organization_id', organizationId)
    .is('deleted_at', null)
    .order('created_at', { ascending: false })
    .limit(300);
  if (status) query = query.eq('status', status);
  const { data } = await query;
  return summarize(sb, (data ?? []) as unknown as QuoteRow[]);
}

export type QuoteDetail = {
  quote: QuoteRow;
  summary: QuoteSummary;
  lines: QuoteLineRow[];
  dossiers: Array<{ id: string; reference: string; learnerName: string }>;
  signatures: Array<{ signerName: string | null; signerEmail: string | null; status: string; createdAt: string; signedAt: string | null }>;
  formationTitle: string | null;
};

export async function loadQuoteDetail(sb: Sb, quoteId: string, organizationId: string): Promise<QuoteDetail | null> {
  const { data } = await sb
    .schema('app')
    .from('quotes')
    .select(QUOTE_COLUMNS)
    .eq('id', quoteId)
    .eq('organization_id', organizationId)
    .is('deleted_at', null)
    .maybeSingle();
  const quote = data as unknown as QuoteRow | null;
  if (!quote) return null;

  const [[summary], { data: lineRows }, { data: links }, { data: sigRows }, { data: fRow }] = await Promise.all([
    summarize(sb, [quote]),
    sb
      .schema('app')
      .from('quote_lines')
      .select('id, position, description, details, quantity, unit_amount_cents, vat_rate')
      .eq('quote_id', quoteId)
      .order('position', { ascending: true }),
    sb.schema('app').from('quote_dossiers').select('dossier_id').eq('quote_id', quoteId),
    quote.document_id
      ? sb
          .schema('app')
          .from('document_signatures')
          .select('signer_name, signer_email, status, created_at, signed_at')
          .eq('document_id', quote.document_id)
          .order('created_at', { ascending: false })
      : Promise.resolve({ data: [] }),
    quote.formation_id
      ? sb.schema('app').from('formations').select('title').eq('id', quote.formation_id).maybeSingle()
      : Promise.resolve({ data: null }),
  ]);

  const dossierIds = ((links ?? []) as Array<{ dossier_id: string }>).map((l) => l.dossier_id);
  const { data: dRows } = dossierIds.length
    ? await sb
        .schema('app')
        .from('dossiers')
        .select('id, reference, learner:learners(first_name, last_name)')
        .in('id', dossierIds)
    : { data: [] };

  return {
    quote,
    summary: summary as QuoteSummary,
    lines: ((lineRows ?? []) as unknown as QuoteLineRow[]).map((l) => ({
      ...l,
      quantity: Number(l.quantity),
      vat_rate: l.vat_rate == null ? null : Number(l.vat_rate),
    })),
    dossiers: (
      (dRows ?? []) as unknown as Array<{
        id: string;
        reference: string;
        learner: { first_name: string; last_name: string } | null;
      }>
    ).map((d) => ({
      id: d.id,
      reference: d.reference,
      learnerName: d.learner ? `${d.learner.first_name} ${d.learner.last_name}`.trim() : '—',
    })),
    signatures: (
      (sigRows ?? []) as Array<{
        signer_name: string | null;
        signer_email: string | null;
        status: string;
        created_at: string;
        signed_at: string | null;
      }>
    ).map((s) => ({
      signerName: s.signer_name,
      signerEmail: s.signer_email,
      status: s.status,
      createdAt: s.created_at,
      signedAt: s.signed_at,
    })),
    formationTitle: (fRow as { title?: string } | null)?.title ?? null,
  };
}
