'use client';

import { useState, useTransition } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Building2, Eye, Loader2, PenLine, Receipt, Send, Sparkles, User } from 'lucide-react';
import { StatusPill } from '@/shared/ui/status-pill';
import { QUOTE_STATUS_LABELS, canSendQuote } from '@/features/billing/domain/quote';
import type { QuoteSummary } from '@/features/billing/quotes/queries';
import { sendQuote } from '../actions';
import { QUOTE_STATUS_TONE, actionError, formatDate, formatEuros } from './labels';

/**
 * Carte d'un devis dans un dossier ou une session : lecture rapide + « Valider
 * et envoyer au client ». L'édition détaillée se fait sur la fiche du devis.
 */
export function QuoteCard({ quote, canManage }: { quote: QuoteSummary; canManage: boolean }) {
  const router = useRouter();
  const [pending, start] = useTransition();
  const [message, setMessage] = useState<{ tone: 'ok' | 'err'; text: string } | null>(null);

  const send = () => {
    setMessage(null);
    if (!quote.recipientEmail) {
      setMessage({ tone: 'err', text: 'Renseignez l’e-mail du destinataire sur la fiche du devis avant l’envoi.' });
      return;
    }
    const verb = quote.status === 'sent' ? 'renvoyé' : 'envoyé';
    if (!window.confirm(`Le devis ${quote.reference} sera ${verb} pour signature à ${quote.recipientEmail}. Continuer ?`)) {
      return;
    }
    start(async () => {
      const res = await sendQuote({ quoteId: quote.id });
      const error = actionError(res);
      if (error) {
        setMessage({ tone: 'err', text: error });
        return;
      }
      setMessage({ tone: 'ok', text: `Devis ${verb} à ${quote.recipientEmail}.` });
      router.refresh();
    });
  };

  const ClientIcon = quote.clientKind === 'company' ? Building2 : User;

  return (
    <div className="bg-white dark:bg-zinc-900 border border-zinc-200/60 dark:border-zinc-800 rounded-xl shadow-sm p-5">
      <div className="flex items-start justify-between gap-4">
        <div className="min-w-0">
          <p className="text-[11px] uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Devis</p>
          <Link
            href={`/devis/${quote.id}`}
            className="text-[17px] font-medium tabular-nums text-zinc-900 dark:text-zinc-100 hover:text-orange-600"
          >
            {quote.reference}
          </Link>
          <p className="text-[13px] text-zinc-600 dark:text-zinc-400 truncate">{quote.object}</p>
        </div>
        <StatusPill tone={QUOTE_STATUS_TONE[quote.status]}>{QUOTE_STATUS_LABELS[quote.status]}</StatusPill>
      </div>

      <dl className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4 text-[13px]">
        <div className="min-w-0">
          <dt className="text-[11px] uppercase tracking-wider text-zinc-500 dark:text-zinc-400 mb-0.5">Client</dt>
          <dd className="flex items-center gap-1.5 text-zinc-900 dark:text-zinc-100 min-w-0">
            <ClientIcon className="w-3.5 h-3.5 shrink-0 text-zinc-400" />
            <span className="truncate">{quote.clientName}</span>
          </dd>
          <dd className="text-[11px] text-zinc-500 dark:text-zinc-400">
            {quote.clientKind === 'company'
              ? `Entreprise · ${quote.learnerCount} stagiaire${quote.learnerCount > 1 ? 's' : ''}`
              : 'Particulier'}
          </dd>
        </div>
        <div>
          <dt className="text-[11px] uppercase tracking-wider text-zinc-500 dark:text-zinc-400 mb-0.5">Montant</dt>
          <dd className="tabular-nums text-zinc-900 dark:text-zinc-100">{formatEuros(quote.totalCents)}</dd>
        </div>
        <div>
          <dt className="text-[11px] uppercase tracking-wider text-zinc-500 dark:text-zinc-400 mb-0.5">Validité</dt>
          <dd className="tabular-nums text-zinc-900 dark:text-zinc-100">{formatDate(quote.validUntil)}</dd>
        </div>
        <div className="min-w-0">
          <dt className="text-[11px] uppercase tracking-wider text-zinc-500 dark:text-zinc-400 mb-0.5">Destinataire</dt>
          <dd className={`truncate ${quote.recipientEmail ? 'text-zinc-900 dark:text-zinc-100' : 'text-amber-600'}`}>
            {quote.recipientEmail ?? 'e-mail à renseigner'}
          </dd>
          {quote.sentAt && (
            <dd className="text-[11px] text-zinc-500 dark:text-zinc-400">Envoyé le {formatDate(quote.sentAt)}</dd>
          )}
        </div>
      </dl>

      {quote.autoGenerated && quote.status === 'draft' && (
        <p className="mt-4 flex items-start gap-2 rounded-lg bg-orange-50/70 dark:bg-orange-950/20 border border-orange-200/60 dark:border-orange-900/40 px-3 py-2 text-[12px] text-orange-900 dark:text-orange-200">
          <Sparkles className="w-3.5 h-3.5 mt-0.5 shrink-0" />
          Établi automatiquement au tarif de la session. Relisez-le, modifiez-le si besoin, puis validez l’envoi au client.
        </p>
      )}

      {message && (
        <p className={`mt-3 text-[12px] ${message.tone === 'ok' ? 'text-emerald-600' : 'text-red-600'}`}>{message.text}</p>
      )}

      <div className="mt-4 flex flex-wrap items-center gap-2">
        <Link
          href={`/devis/${quote.id}`}
          className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-200/70 dark:border-zinc-700 px-3 py-1.5 text-[13px] text-zinc-700 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition"
        >
          <PenLine className="w-3.5 h-3.5" />
          {quote.status === 'draft' && canManage ? 'Voir et modifier' : 'Ouvrir'}
        </Link>
        {quote.documentId && (
          <Link
            href={`/documents/${quote.documentId}/apercu`}
            className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-200/70 dark:border-zinc-700 px-3 py-1.5 text-[13px] text-zinc-700 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition"
          >
            <Eye className="w-3.5 h-3.5" />
            Aperçu
          </Link>
        )}
        {quote.invoice && (
          <Link
            href="/factures"
            className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-200 dark:border-emerald-900/60 px-3 py-1.5 text-[13px] text-emerald-700 dark:text-emerald-300 hover:bg-emerald-50 dark:hover:bg-emerald-950/30 transition"
          >
            <Receipt className="w-3.5 h-3.5" />
            Facture {quote.invoice.reference.startsWith('PROV-') ? 'brouillon' : quote.invoice.reference}
          </Link>
        )}
        {canManage && canSendQuote(quote.status) && (
          <button
            type="button"
            onClick={send}
            disabled={pending}
            className="ml-auto inline-flex items-center gap-1.5 rounded-lg bg-orange-500 hover:bg-orange-600 disabled:opacity-50 text-white text-[13px] font-medium px-3.5 py-2 shadow-sm transition"
          >
            {pending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
            {quote.status === 'sent' ? 'Renvoyer au client' : 'Valider et envoyer au client'}
          </button>
        )}
      </div>
    </div>
  );
}
